CONTA_ACEITE = "A sua conta foi aceite com sucesso!"
CONTA_REJEITADA = "A sua conta não foi aceite!"
CONTA_NAO_ACTIVADA = "A sua conta não foi activada coretamente"
ACTIVACAO_DA_CONTA = "SIIA - Verificação de Email"
VERIFICACAO_DE_EMAIL = "SIIA - Verificação de Email"
